service:
  name: gmeet-slash-cmd

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  profile: ${file(./config.json):profile}
  timeout: 15
  apiGateway:
    minimumCompressionSize: 512
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    CLIENT_ID: ${file(./config.json):clientId}
    CLIENT_SECRET: ${file(./config.json):clientSecret}
    REDIRECT_URL: ${file(./config.json):redirectUrl}
    AWS_REGION: ${self:provider.region}
    S3_BUCKET_NAME: ${file(./config.json):s3BucketName}
    LAMBDA_URL: ${file(./config.json):lambdaUrl}

functions:
  auth:
    handler: handler.auth
    events:
      - http:
          method: get
          path: auth
  callback:
    handler: handler.callback
    events:
      - http:
          method: get
          path: callback
  create:
    handler: handler.create
    events:
      - http:
          method: post
          path: create
